url: "https://gitpress.soraxem.ch"
raw-repo: "https://raw.githubusercontent.com/Soraxem/gitpress/main/"
baseurl: "/"
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "songs"
    values:
      layout: "song"
